# Change these first
owner: afgalvan # Your GitHub organization or username, where this repository lives
repo: pinstatus # The name of this repository

sites:
  - name: Web
    url: https://pinapp.vercel.app/
  - name: API
    url: https://jixlrpxlttgacozsxqcn.supabase.co/functions/v1/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /pinstatus
  logoUrl: https://pinapp.vercel.app/favicon.svg
  name: Pinapp Status Page
  introTitle: "**Pinapp** is college project for managing processes on a local fabric."
  introMessage: Status Page for the pinapp web application
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
